#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network )

if [ $# -ne ${#required_args[@]} ]; then
  description="Fetch new token prices and post them to the PriceOracle. This script will be ran periodically by the server, so we do not need to run it by hand."
  show_help_message "$description" $required_args
  exit 1
fi

run_truffle_script "$@"
