#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network is_lock_user_actions )

if [ $# -ne ${#required_args[@]} ]; then
  description="Set user actions lock status to unlock or lock"
  show_help_message "$description" $required_args
  exit 1
fi

run_truffle_script "$@"
