pragma solidity ^0.6.0;

interface IStruct {
    struct DepositRecord {
        bytes32 depositId;
        address payable ownerAddress;
        address tokenAddress;
        uint256 depositTerm;
        uint256 depositAmount;
        uint256 poolId;
        uint256 createdAt;
        uint256 withdrewAt;
        uint256 weight;
        address payable distributorAddress;
    }

    struct GetDepositRecordResponse {
        bytes32 depositId;
        address tokenAddress;
        uint256 depositTerm;
        uint256 depositAmount;
        uint256 poolId;
        uint256 interest;
        uint256 createdAt;
        uint256 withdrewAt;
        uint256 weight;
    }

    struct LoanRecord {
        bool isClosed;
        bytes32 loanId;
        address payable ownerAddress;
        address loanTokenAddress;
        address collateralTokenAddress;
        uint256 loanAmount;
        uint256 collateralAmount;
        uint256 loanTerm;
        uint256 annualInterestRate;
        uint256 interest;
        uint256 minCollateralCoverageRatio;
        uint256 liquidationDiscount;
        uint256 alreadyPaidAmount;
        uint256 liquidatedAmount;
        uint256 soldCollateralAmount;
        uint256 createdAt;
        uint256 dueAt;
        uint256 lastInterestUpdatedAt;
        uint256 lastRepaidAt;
        uint256 lastLiquidatedAt;
        address payable distributorAddress;
        uint256 distributorInterest;
    }

    struct GetLoanRecordResponse {
        bool isClosed;
        bytes32 loanId;
        address loanTokenAddress;
        address collateralTokenAddress;
        uint256 loanAmount;
        uint256 collateralAmount;
        uint256 loanTerm;
        uint256 annualInterestRate;
        uint256 interest;
        uint256 currentCollateralRatio;
        uint256 minCollateralCoverageRatio;
        uint256 alreadyPaidAmount;
        uint256 soldCollateralAmount;
        uint256 createdAt;
        uint256 dueAt;
        uint256 remainingDebt;
    }

    struct LoanAndCollateralTokenPair {
        bool isEnabled;
        address loanTokenAddress;
        address collateralTokenAddress;
        uint256 minCollateralCoverageRatio;
        uint256 liquidationDiscount;
    }

    struct Pool {
        // Total amount deposited to this pool
        uint256 depositAmount;
        // Total amount that can be borrowed from this pool
        uint256 availableAmount;
        /// We add loan interest generated by a specific loan amount from this pool.
        /// It will be used to calculate interest for whom deposited to this pool.
        uint256 loanInterest;
        // Total deposit weight
        uint256 totalDepositWeight;
        /// We store interest disribution ratios when the very first deposit is made and
        /// they can't be changed afterwards to ensure correct interest calculation
        uint256 depositDistributorFeeRatio;
        uint256 loanDistributorFeeRatio;
        uint256 protocolReserveRatio;
    }

    struct getPoolsByTokenResponse {
        uint256 poolId;
        uint256 depositAmount;
        uint256 availableAmount;
        uint256 loanInterest;
        uint256 totalDepositWeight;
    }

    struct DepositParameters {
        address tokenAddress;
        uint256 depositAmount;
        uint256 depositTerm;
        address payable distributorAddress;
    }

    struct LoanParameters {
        address loanTokenAddress;
        address collateralTokenAddress;
        uint256 loanAmount;
        uint256 collateralAmount;
        uint256 loanTerm;
        address payable distributorAddress;
    }
}
