#!/bin/bash

set -eo pipefail

if [[ "$1" == "help" || "$#" -ne 1 ]]; then
  echo "Disable an asset for deposit. The target asset must not be already disabled."
  echo "Usage: ./scripts/bash/disableDepositAsset <token_symbol>"
  echo "Where <token_symbol> can be ETH/DAI/USDC"
  exit 1
fi

DIR=`dirname $0`
token_symbol="$1"

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/disableDepositAsset.js" $token_symbol
