#!/bin/bash

set -eo pipefail

if [[ "$1" == "help" || "$#" -ne 2 ]]; then
  echo "Disable an asset pair for loan. The target asset pair must not be already disabled."
  echo "Usage: ./scripts/bash/disableLoanAssetPair <loan_token_symbol> <collateral_token_symbol>"
  echo "Where <loan_token_symbol> and <collateral_token_symbol> can be ETH/DAI/USDC, but both can't be the same."
  exit 1
fi

DIR=`dirname $0`
loan_token_symbol="$1"
collateral_token_symbol="$2"

npx truffle compile

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/disableLoanAssetPair.js" $loan_token_symbol $collateral_token_symbol
