#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network )

if [ $# -ne ${#required_args[@]} ]; then
  description="Enable token pairs for loan. The target asset pair must not be already enabled."
  example_args="development"
  show_help_message "$description" $required_args "$example_args"
  exit 1
fi

run_truffle_script "$@"
