#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network timeInDays )

if [ $# -ne ${#required_args[@]} ]; then
  description="Increase the time."
  example_args="development 1"
  show_help_message "$description" $required_args "$example_args"
  exit 1
fi

run_truffle_script "$@"
