#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network token_symbol account_address decimal_value )

if [ $# -ne ${#required_args[@]} ]; then
  description="Mint tokens to an account."
  show_help_message "$description" $required_args
  exit 1
fi

run_truffle_script "$@"
