#!/bin/bash

set -eo pipefail

if [[ "$1" == "help" || "$#" -ne 3 ]]; then
  echo "Set collateral ratio for a given pair of loan and collateral token."
  echo "Usage: ./scripts/bash/setCollateralRatio <loan_token_symbol> <collateral_token_symbol> <decimal_value>"
  echo "Where <loan_token_symbol> and <collateral_token_symbol> can be ETH/DAI/USDC, but both can't be the same."
  exit 1
fi

DIR=`dirname $0`
loan_token_symbol="$1"
collateral_token_symbol="$2"
decimal_value="$3"

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/setCollateralRatio.js" $loan_token_symbol $collateral_token_symbol $decimal_value
