#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network loan_token_symbol collateral_token_symbol )

if [ $# -ne ${#required_args[@]} ]; then
  description="Set collateral ratio for a given pair of loan and collateral token."
  show_help_message "$description" $required_args
  exit 1
fi

run_truffle_script "$@"
