#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network, price )

if [ $# -ne ${#required_args[@]} ]; then
  description="Set ETH price in dollar."
  example_args="development 2500"
  show_help_message "$description" $required_args "$example_args"
  exit 1
fi

run_truffle_script "$@"
