#!/bin/bash

set -eo pipefail

if [[ "$1" == "help" || "$#" -ne 3 ]]; then
  echo "Set loan interest rate for an asset with a specific term."
  echo "Usage: ./scripts/bash/setLoanInterestRate <token_symbol> <loan_term> <decimal_value>"
  echo "Where <token_symbol> can be ETH/DAI/USDC, <loan_term> can be 1/7/30"
  exit 1
fi

DIR=`dirname $0`
token_symbol="$1"
loan_term="$2"
decimal_value="$3"

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/setLoanInterestRate.js" $token_symbol $loan_term $decimal_value
