#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network decimal_value )

if [ $# -ne ${#required_args[@]} ]; then
  description="Set protocol reserve ratio."
  show_help_message "$description" $required_args
  exit 1
fi

run_truffle_script "$@"
