#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network, token, price )

if [ $# -ne ${#required_args[@]} ]; then
  description="Set the price for a token using a single feed price oracle."
  show_help_message "$description" $required_args
  exit 1
fi

run_truffle_script "$@"
