#!/bin/bash

set -eo pipefail

if [ "$1" == "help" ]; then
  echo "Set shareholder address to a newly created address. This is for testing only."
  echo "Usage: ./scripts/bash/setShareholderAddressForTest"
  exit 1
fi

DIR=`dirname $0`

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/setShareholderAddressForTest.js"
