#!/bin/bash

set -eo pipefail

if [ "$1" == "help" ]; then
  echo "Reset and initialize contract state for test environment."
  echo "Usage: ./scripts/bash/setupEnvironment"
  exit 1
fi

DIR=`dirname $0`

npx truffle migrate --reset

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/setupEnvironment.js"
