#!/bin/bash

set -eo pipefail

if [[ "$1" == "help" || "$#" -ne 1 ]]; then
  echo "Unpause a contract that inherits from Pausable contract."
  echo "Usage: ./scripts/bash/unpauseContract <contract_name>"
  echo "Example: ./scripts/bash/unpauseContract DepositManager"
  exit 1
fi

DIR=`dirname $0`
contract_name="$1"

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/unpauseContract.js" $contract_name
