#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=( network contract_name )

if [ $# -ne ${#required_args[@]} ]; then
  description="Unpause a contract that inherits from Pausable contract."
  example_args="development DepositManager"
  show_help_message "$description" $required_args "$example_args"
  exit 1
fi

run_truffle_script "$@"
