#!/bin/bash

set -eo pipefail

if [ "$1" == "help" ]; then
  echo "Update interest index histories for all enabled deposit assets."
  echo "Usage: ./scripts/bash/updateInterestIndexHistories"
  exit 1
fi

DIR=`dirname $0`

npx truffle compile

env DEBUG='script:*' npx truffle exec "$DIR/../javascript/updateInterestIndexHistories.js"
