#!/bin/bash

DIR=`dirname $0`
source $DIR/utils

required_args=(network)

if [ $# -ne ${#required_args[@]} ]; then
  description="Compare the protocol configs and config file."
  show_help_message "$description" $required_args
  exit 1
fi

run_truffle_script "$@"
