module.exports = {
  contract: {
    tokens: {
      USDT: {
        name: 'Tether',
        loanInterestRateLowerBound: 0.08,
        loanInterestRateUpperBound: 0.1,
        balanceCap: 1000000,
      },
      WETH: {
        name: 'Wrapped Ether',
        loanInterestRateLowerBound: 0.06,
        loanInterestRateUpperBound: 0.08,
        balanceCap: 10000,
      },
    },
    depositTerms: [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      // 8,
      // 9,
      // 10,
      // 11,
      // 12,
      // 13,
      // 14,
      // 15,
      // 16,
      // 17,
      // 18,
      // 19,
      // 20,
      // 21,
      // 22,
      // 23,
      // 24,
      // 25,
      // 26,
      // 27,
      // 28,
      // 29,
      // 30,
    ],
    loanAndCollateralTokenPairs: [
      {
        loanTokenSymbol: 'USDT',
        collateralTokenSymbol: 'WETH',
        minCollateralCoverageRatio: 1.3,
        liquidationDiscount: 0.05,
      },
    ],
    protocolReserveRatio: 0,
    depositDistributorFeeRatio: 0.05,
    loanDistributorFeeRatio: 0.05,
    interestReserveAddress: '0xf4Cb4Decc09CAdA4e4DCd510d915A5d9E5C8DE71',
  },
};
